### ISSUE TITLE
Visual bug in landscape mode in iOS8

### ISSUE THREAD

**Issue by sarbogast** [romaonthego/REMenu#97]
![capture d ecran 2014-11-17 15 47 53](https://cloud.githubusercontent.com/assets/143758/5080157/34ba163a-6e71-11e4-9811-77c262b79a46.png)

**Comment by romaonthego** [comment]
Yeah, the status bar is tricky in iOS8. You can specify `prefersStatusBarHidden` to `NO` in this view controller to avoid this behavior.
