### ISSUE TITLE
Any advice on implementing this within a UITabBarController?

### ISSUE THREAD

**Issue by simonpac** [romaonthego/REMenu#99]
I'm wondering if anybody has had any success in implementing this menu with a UITabBarController?

**Comment by chrise86** [comment]
Did you get anywhere with this @simonpac ?

**Comment by simonpac** [comment]
Yes I had to implement it myself. It was not conventional but it works :-)

On Feb 26, 2015, at 5:45 AM, Chris Edwards <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you get anywhere with this @simonpac<https://github.com/simonpac> ?

-

**Comment by chrise86** [comment]
@simonpac ah ok, what about the "dropping up" instead of down?
